// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenZipProject
{
    internal sealed partial class Vsix
    {
        public const string Id = "75295161-4c91-4eea-85e5-4c01f831e831";
        public const string Name = "Open Zip Project";
        public const string Description = @"Allows you to open projects that have been zipped up into .zip files either from the local file sytem or remote URLs";
        public const string Language = "en-US";
        public const string Version = "1.0.99999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
