// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenZipProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "d2822e1b-2c7a-44b2-9be3-50a0428e5995";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenZipProjectCmdString = "7946e212-a522-4445-b2d4-6dd240228eab";
        public static Guid guidOpenZipProjectCmd = new Guid(guidOpenZipProjectCmdString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int OpenZipFileCommandId = 0x0100;
    }
}